common: &common
  adapter: postgresql
  username: tyler
  password: 123456
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: programming_challenges_dev

test:
  <<: *common
  database: programming_challenges_test

